[package]

name = "hiprust"
version = "0.0.0"
authors = ["Peter Schuller <peter.schuller@infidyne.com>"]

[lib]
name = "hiprust"
path = "src/hiprust/lib.rs"

[dependencies]
rustc-serialize = "0.2"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http"
